1712873061092	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1712873168980	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1712873168980	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1712873168981	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1712873168982	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1712873174550	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1712873174550	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1712873174552	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1712873174552	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.1 (Linux x86_64) FxSync/1.126.0.20240321230221.desktop
1712873174552	Sync.Service	INFO	Starting sync at 2024-04-12 00:06:14 in browser session j_-OnZB2FHbk
1712873174552	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1712873174554	Sync.Status	INFO	Resetting Status.
1712873174554	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1712873174554	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1712873174582	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1712873174583	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1712873174583	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1712873174583	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1712873174583	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1712873174585	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
