1713002507057	Sync.LogManager	DEBUG	Flushing file log
1713002507058	Sync.LogManager	DEBUG	Log cleanup threshold time: 1712138507058
1713002507062	Sync.LogManager	DEBUG	Done deleting files.
1713002507083	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713002507083	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713002696413	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.1 (Linux x86_64) FxSync/1.126.0.20240321230221.desktop
1713002696413	Sync.Service	INFO	Starting sync at 2024-04-13 12:04:56 in browser session YYQHhDZxWf3d
1713002696413	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713002696415	Sync.Status	INFO	Resetting Status.
1713002696415	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1713002696415	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1713002696415	FirefoxAccounts	DEBUG	getOAuthToken enter
1713002696415	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713002696415	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713002696415	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1713002696415	Sync.SyncAuthManager	INFO	Getting sync key
1713002696415	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1713002696415	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1713002696415	FirefoxAccounts	DEBUG	getOAuthToken enter
1713002696416	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713002696416	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713002696416	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1713002696416	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1713002736457	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713002736458	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713002736458	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713002736458	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713002736459	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1713002736459	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1713002736459	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713002736459	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1713002802739	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1713002802739	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1713002802739	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1713002802739	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1713002802740	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1713002802740	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1713002802745	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
